spring:
  application:
    name: msavaliadorcredito

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://lnr:lnr@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes